---- 관리자 계정에서 계정 생성
---- ID: COWORKS
---- PW: COWORKS_
--
--CREATE USER COWORKS IDENTIFIED BY COWORKS_;
--GRANT CONNECT, RESOURCE, CREATE VIEW TO COWORKS;
--
----------------------------------------------------------
-- 테이블 삭제 폼
DROP TABLE APPROVATTACH CASCADE CONSTRAINTS;
DROP TABLE APPROVDOC CASCADE CONSTRAINTS;
DROP TABLE APPROVFORM CASCADE CONSTRAINTS;
DROP TABLE APPROVSTATUS CASCADE CONSTRAINTS;
DROP TABLE ATTACH CASCADE CONSTRAINTS;
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP TABLE AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARDGROUP CASCADE CONSTRAINTS;
DROP TABLE CALENDAR CASCADE CONSTRAINTS;
DROP TABLE CHAT CASCADE CONSTRAINTS;
DROP TABLE CHATROOM CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE EDUAPPLY CASCADE CONSTRAINTS;
DROP TABLE EDUCATION CASCADE CONSTRAINTS;
DROP TABLE EDUREPORT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE JOB CASCADE CONSTRAINTS;
DROP TABLE MAIL CASCADE CONSTRAINTS;
DROP TABLE MFOLDER CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE PAY CASCADE CONSTRAINTS;
DROP TABLE SURVEY CASCADE CONSTRAINTS;
DROP TABLE SURVEYANSWER CASCADE CONSTRAINTS;
DROP TABLE SURVEYAPPLY CASCADE CONSTRAINTS;
DROP TABLE TODO CASCADE CONSTRAINTS;

-- 시퀀스 삭제 폼
DROP SEQUENCE SEQ_CNO; --첨부파일(ATTACH)
DROP SEQUENCE SEQ_CNO; --게시판(BOARD)
DROP SEQUENCE SEQ_CNO; --게시판그룹(BOARDGROUP)
DROP SEQUENCE SEQ_CNO; --일정(CALENDAR)
DROP SEQUENCE SEQ_CNO; --메일(MAIL)
DROP SEQUENCE SEQ_CNO; --메일폴더(MFOLDER)
DROP SEQUENCE SEQ_CNO; --공지(NOTIFICATION)
DROP SEQUENCE SEQ_CNO; --설문(SURVEY)
DROP SEQUENCE SEQ_CNO; --설문응답(SURVEYANSWER)
DROP SEQUENCE SEQ_CNO; --설문등록(SURVEYAPPLY)
DROP SEQUENCE SEQ_CNO; --결재첨부(APPROVATTACH)
DROP SEQUENCE SEQ_CNO; --결재파일(APPROVDOC)
DROP SEQUENCE SEQ_CNO; --결재폼(APPROVFORM)
DROP SEQUENCE SEQ_CNO; --결재상태(APPROVSTATUS)
DROP SEQUENCE SEQ_CNO; --근태(ATTENDANCE)
DROP SEQUENCE SEQ_CNO; --권한(AUTHORITY)
DROP SEQUENCE SEQ_CNO; --부서(DEPARTMENT)
DROP SEQUENCE SEQ_CNO; --사원(EMPLOYEE)
DROP SEQUENCE SEQ_CNO; --직급(JOB)
DROP SEQUENCE SEQ_CNO; --할일(TODO)
DROP SEQUENCE SEQ_CNO; --교육(EDUCATION)
DROP SEQUENCE SEQ_CNO; --채팅(CHAT)
DROP SEQUENCE SEQ_CNO; --교육신청(EDUAPPLY)
DROP SEQUENCE SEQ_CNO; --채팅방(CHATROOM)
DROP SEQUENCE SEQ_CNO; --교육보고서(EDUREPORT)
DROP SEQUENCE SEQ_CNO; --월급(PAY)

---- 시퀀스 생성 폼
--CREATE SEQUENCE SEQ_CNO
--START WITH 1
--INCREMENT BY 1
--NOCYCLE
--NOCACHE;
   
   
     CREATE TABLE "MAIL" --메일
   (	
    "MAIL_NO" NUMBER, 
	"MAIL_SUBJECT" VARCHAR2(1000), 
	"MAIL_CONTENT" VARCHAR2(4000), 
	"MAIL_SENDDATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"MAIL_ISREAD" VARCHAR2(10) DEFAULT('N'), 
	"MAIL_FROMDEL" VARCHAR2(10) DEFAULT('N'), 
	"MAIL_TODEL" VARCHAR2(10) DEFAULT('N'), 
	"MAIL_STAR" VARCHAR2(10) DEFAULT('N'),
    "MAIL_MARK" NUMBER  DEFAULT(6), 
	"MAIL_TO_EMAIL" VARCHAR2(100), 
	"MAIL_FROM_EMAIL" VARCHAR2(100), 
	"MAIL_NAME" VARCHAR2(100) 
   ) ;


  CREATE TABLE "ATTACH" -- 첨부파일
   (   "ATTACH_NO" NUMBER, 
   "BO_NO" NUMBER, 
   "ATTACH_ORINAME" VARCHAR2(1000), 
   "ATTACH_RENAME" VARCHAR2(1000), 
   "ATTACH_PATH" VARCHAR2(1000)
   ) ;

   
   
   
   
     CREATE TABLE "BOARD" --게시판
   (   "BO_NO" NUMBER, 
   "BO_CODE" VARCHAR2(100), 
   "BO_TITLE" VARCHAR2(1000), 
   "BO_CONTENT" VARCHAR2(4000), 
   "EMP_NO" NUMBER, 
   "BO_DATE" TIMESTAMP (6) default sysdate, 
   "BO_STATUS" VARCHAR2(100) default 'y'
   ) ;
   
    INSERT INTO BOARD VALUES(1, 'CD', '게시판 1번 글', '게시판 1번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(1, 'BD', '게시판 1번 글', '게시판 1번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(1, 'DD', '게시판 1번 글', '게시판 1번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(1, 'ED', '게시판 1번 글', '게시판 1번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(2, 'CD', '게시판 2번 글', '게시판 2번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(2, 'BD', '게시판 2번 글', '게시판 2번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(2, 'ED', '게시판 2번 글', '게시판 2번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(2, 'DD', '게시판 2번 글', '게시판 2번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(3, 'CD', '게시판 3번 글', '게시판 3번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(3, 'BD', '게시판 3번 글', '게시판 3번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(3, 'ED', '게시판 3번 글', '게시판 3번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(3, 'DD', '게시판 3번 글', '게시판 3번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(4, 'CD', '게시판 4번 글', '게시판 4번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(4, 'BD', '게시판 4번 글', '게시판 4번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(4, 'ED', '게시판 4번 글', '게시판 4번 내용', 12345678, DEFAULT, DEFAULT);
    INSERT INTO BOARD VALUES(4, 'DD', '게시판 4번 글', '게시판 4번 내용', 12345678, DEFAULT, DEFAULT);
   
   
   
   
     CREATE TABLE "BOARDGROUP" --게시판그룹
   (   "BG_NO" NUMBER, 
   "BG_CODE" VARCHAR2(100), 
   "BG_TITLE" VARCHAR2(1000)
   ) ;
   
   INSERT INTO BOARDGROUP VALUES (1, 'CD', '사내규정 자료실');
   INSERT INTO BOARDGROUP VALUES (2, 'BD', '업무자료 자료실');
   INSERT INTO BOARDGROUP VALUES (3, 'ED', '교육자료 자료실');
   INSERT INTO BOARDGROUP VALUES (4, 'DD', '부서별 자료실');
   INSERT INTO BOARDGROUP VALUES (5, 'NB', '공지사항 게시판');
   INSERT INTO BOARDGROUP VALUES (6, 'FB', '경조사 게시판');
   INSERT INTO BOARDGROUP VALUES (7, 'RB', '조직개편 및 인사이동 게시판');
   INSERT INTO BOARDGROUP VALUES (8, 'SB', 'News 게시판');
   INSERT INTO BOARDGROUP VALUES (9, 'BB', '자유게시판');
   INSERT INTO BOARDGROUP VALUES (10, 'DB', '부서별 게시판');
   
   
   
   
  CREATE TABLE "BOARDATTACH"  --게시판 첨부파일
   (   "BDATTACH_NO" NUMBER, 
   "BO_NO" NUMBER, 
   "ORIGINALFILENAME" VARCHAR2(255), 
   "RENAMEDFILENAME" VARCHAR2(255), 
   "DOWNLOADCOUNT" NUMBER DEFAULT 0, 
   "STATUS" VARCHAR2(20) DEFAULT 'Y'
   ) ;
   
   
   
     CREATE TABLE "CALENDAR" --일정
   (   "CAL_NO" NUMBER, 
   "CAL_HOLDER" VARCHAR2(100), 
   "CAL_TYPE" VARCHAR2(100), 
   "CAL_NAME" VARCHAR2(1000), 
   "CAL_CONTENT" VARCHAR2(4000), 
   "CAL_BEGINDATE" TIMESTAMP (6), 
   "CAL_ENDDATE" TIMESTAMP (6)
   ) ;
   
   
   
   
   
     CREATE TABLE "MAIL" --메일
   (   "MAIL_NO" NUMBER, 
   "MAIL_FORM" NUMBER, 
   "MAIL_TO" NUMBER, 
   "MAIL_SUBJECT" VARCHAR2(1000), 
   "MAIL_CONTENT" VARCHAR2(4000), 
   "MAIL_SENDDATE" TIMESTAMP (6), 
   "MAIL_READDATE" TIMESTAMP (6), 
   "MAIL_ISREAD" VARCHAR2(10), 
   "MAIL_FROMDEL" VARCHAR2(10), 
   "MAIL_TODEL" VARCHAR2(10), 
   "MFOLDER_NO" NUMBER, 
   "MAIL_ATTACHPATH" VARCHAR2(1000)
   ) ;
   
   
   
   
   
   
     CREATE TABLE "MFOLDER" --메일폴더
   (   "MFOLDER_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "MFOLDER_NAME" VARCHAR2(300)
   ) ;
   
   
   
   
   
     CREATE TABLE "NOTIFICATION" --공지
   (   "NOTI_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "NOTI_TYPE" VARCHAR2(100), 
   "NOTI_CONTENT" VARCHAR2(4000), 
   "NOTI_DATE" TIMESTAMP (6) DEFAULT SYSDATE
   ) ;
   
   
   
   
   
   
     CREATE TABLE "SURVEY" --설문
   (   "SURVEY_NO" NUMBER, 
   "SURVEY_QUEST" VARCHAR2(3000), 
   "SURVEY_START" TIMESTAMP (6), 
   "SURVEY_END" TIMESTAMP (6)
   ) ;
   
   
   
   
   
     CREATE TABLE "SURVEYANSWER" --설문응답
   (   "SURVEYAN_NO" NUMBER, 
   "SURVEY_NO" NUMBER, 
   "SURVEY_CONTENT" VARCHAR2(4000)
   ) ;
   
   
   
   
   
     CREATE TABLE "SURVEYAPPLY" --설문등록
   (   "SURVEYAPP_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "SURVEY_NO" NUMBER
   ) ;
   
   
   
   
   

  CREATE TABLE "APPROVALATTACH" --결재첨부
   (   "APATT_NO" NUMBER, 
   "ADOC_NO" NUMBER, 
   "APATT_ORINAME" VARCHAR2(1000), 
   "APATT_RENAME" VARCHAR2(1000), 
   "APATT_PATH" VARCHAR2(1000)
   );






  CREATE TABLE "APPROVALDOC" --결재서류
   (   "ADOC_NO" NUMBER, 
   "AFORM_NO" NUMBER, 
   "ADOC_WRITERNO" NUMBER, 
   "ADOC_UPLOADDATE" TIMESTAMP (6), 
   "ADOC_SECURITY" NUMBER, 
   "ADOC_EXPIRATION" DATE, 
   "ADOC_SUBJECT" VARCHAR2(1000), 
   "ADOC_CONTENT" VARCHAR2(4000), 
   "ADOC_STATE" VARCHAR2(1000)
   );







  CREATE TABLE "APPROVALFORM" --결재폼
   (   "AFORM_NO" NUMBER, 
   "AFORM_TITLE" VARCHAR2(1000), 
   "AFORM_FOLDERNAME" VARCHAR2(1000), 
   "AFORM_FORMPAGE" VARCHAR2(1000), 
   "AFORM_DOCPAGE" VARCHAR2(1000)
   );


--
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (1,'휴가신청서','공용문서','WriteLeaveApplication.do',null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (2,'지출품의서','공용문서','WriteExpenseReport.do',null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (3,'시말서','공용문서',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (4,'기안서','공용문서',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (5,'개발일정표','개발부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (6,'개발완료보고서','개발부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (7,'개발시행품의서','개발부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (8,null,'경리부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (9,null,'총무부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (10,null,'관리부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (11,null,'경영지원부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (12,null,'영업부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (13,null,'기획부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (14,null,'무역부',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (15,'출장여비청구서','공용문서',null,null);
--Insert into COWORKS.APPROVALFORM (AFORM_NO,AFORM_TITLE,AFORM_FOLDERNAME,AFORM_FORMPAGE,AFORM_DOCPAGE) values (16,'회의록','공용문서',null,null);


  CREATE TABLE "APPROVALSTATUS" --결재상태
   (   "AS_NO" NUMBER, 
   "ADOC_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "AS_STATUS" VARCHAR2(100), 
   "AS_DATE" DATE
   );








  CREATE TABLE "ATTENDANCE" --근태
   (   "ATTEN_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "ATTEN_DATE" DATE, 
   "ATTEN_ATTTIME" TIMESTAMP (6), 
   "ATTEN_LEAVETIME" TIMESTAMP (6), 
   "ATTEN_ATTIP" VARCHAR2(100), 
   "ATTEN_LEAVEIP" VARCHAR2(100), 
   "ATTEN_STATE" VARCHAR2(100)
   );








  CREATE TABLE "AUTHORITY" --권한
   (   "EMP_NO" NUMBER, 
   "AUTH_PERSONNAL" VARCHAR2(100), 
   "AUTH_DATA" VARCHAR2(100), 
   "AUTH_CAL" VARCHAR2(100), 
   "AUTH_BOARD" VARCHAR2(100), 
   "AUTH_APPROVAL" VARCHAR2(100), 
   "AUTH_AUTHORITY" VARCHAR2(100), 
   "AUTH_PAY" VARCHAR2(100)
   );








  CREATE TABLE "DEPARTMENT" --부서
   (   "DEPT_CODE" VARCHAR2(20), 
   "DEPT_NAME" VARCHAR2(100), 
   "DEPT_MGRNO" NUMBER, 
   "DEPT_SUP" VARCHAR2(100), 
   "DEPT_LEVEL" NUMBER
   );



   


  CREATE TABLE "EMPLOYEE" --사원
   (   "EMP_NO" NUMBER(8,0), 
   "EMP_NAME" VARCHAR2(20), 
   "EMP_PASSWORD" VARCHAR2(100),
   "JOB_CODE" VARCHAR2(100), 
   "DEPT_CODE" VARCHAR2(100), 
   "EMP_PHONE" VARCHAR2(100), 
   "EMP_EMAIL" VARCHAR2(300), 
   "EMP_EMAILPASSWORD" VARCHAR2(100),
   "EMP_BIRTH" DATE, 
   "EMP_GENDER" VARCHAR2(5), 
   "EMP_HIREDATE" DATE, 
   "EMP_RESIGNDATE" DATE, 
   "EMP_ISWORK" VARCHAR2(5), 
   "EMP_SIGNATURE" VARCHAR2(200),
   EMP_AUTHORITY VARCHAR2(100)
   );







  CREATE TABLE "JOB" --직급
   (   "JOB_CODE" VARCHAR2(20), 
   "JOB_TITLE" VARCHAR2(30)
   );





   
   ----------------------------------------
  CREATE TABLE "TODO" --할 일
   (   "TODO_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "TODO_CONTENT" VARCHAR2(4000), 
   "TODO_ENDDATE" DATE
   );
   





   
   
     CREATE TABLE "EDUCATION" --교육
   (   "EDU_NO" NUMBER, 
   "EDU_TITLE" VARCHAR2(1000), 
   "EDU_INSTRUCTOR" VARCHAR2(100), 
   "EDU_TYPE" VARCHAR2(100), 
   "EDU_LIMITCNT" NUMBER, 
   "EDU_CURCNT" NUMBER, 
   "EDU_APPLYBGDATE" TIMESTAMP (6), 
   "EDU_APPLYENDDATE" TIMESTAMP (6), 
   "EDU_APPLYSTATE" VARCHAR2(100), 
   "EDU_IMAGE" VARCHAR2(1000)
   );





   
   
     CREATE TABLE "CHAT" --채팅
   (   "CHAT_NO" NUMBER, 
   "CROOM_NO" NUMBER, 
   "CHAT_SENDNO" NUMBER, 
   "CHAT_CONTENT" VARCHAR2(4000), 
   "CHAT_SENDTIME" TIMESTAMP (6), 
   "CHAT_ISREAD" VARCHAR2(10)
   );
   





   
     CREATE TABLE "EDUAPPLY" --교육신청
   (   "EAPP_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "EDU_NO" NUMBER
   );
   





   
     CREATE TABLE "CHATROOM" --채팅방
   (   "CROOM_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "CROOM_TITLE" VARCHAR2(1000)
   );
   





   
     CREATE TABLE "EDUREPORT" --교육보고서
   (   "EDUREP_NO" NUMBER, 
   "EDU_NO" NUMBER, 
   "EMP_NO" NUMBER, 
   "EDUREP_TITLE" VARCHAR2(1000), 
   "EDUREP_CONTENT" VARCHAR2(4000), 
   "EDUREP_DATE" TIMESTAMP (6) DEFAULT SYSDATE
   );
   





   
     CREATE TABLE "PAY" --월급
   (   "EMP_NO" NUMBER, 
   "PAY_BASEPAY" NUMBER, 
   "PAY_JOBTITLE" NUMBER, 
   "PAY_OVERTIME" NUMBER, 
   "PAY_HOLLYDAY" NUMBER, 
   "PAY_BONUS" NUMBER, 
   "PAY_MEAL" NUMBER, 
   "PAY_TRANSPORT" NUMBER, 
   "PAY_WELFARE" NUMBER, 
   "PAY_OTHERS" NUMBER, 
   "PAY_TOTAL" NUMBER, 
   "PAY_DATE" DATE
   );


  CREATE TABLE "COWORKS"."CALENDAR"  -- 캘린더 
   (   "CAL_NO" NUMBER, 
   "CAL_HOLDER" VARCHAR2(100 BYTE), 
   "CAL_TYPE" VARCHAR2(100 BYTE), 
   "CAL_COLOR" VARCHAR2(20 BYTE), 
   "CAL_NAME" VARCHAR2(1000 BYTE), 
   "CAL_CONTENT" VARCHAR2(4000 BYTE), 
   "CAL_BEGINDATE" TIMESTAMP (6), 
   "CAL_ENDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   -- calendar 시퀀스
   CREATE SEQUENCE  "COWORKS"."SEQ_CALENDAR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 110 NOCACHE  NOORDER  NOCYCLE ;
   
   CREATE SEQUENCE  "COWORKS"."SEQ_MAIL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 110 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "COWORKS"."SEQ_MAIL_ATTACH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 110 NOCACHE  NOORDER  NOCYCLE ;
   
   
   
Insert into COWORKS.JOB (JOB_CODE,JOB_TITLE) values ('J1','부장');
Insert into COWORKS.JOB (JOB_CODE,JOB_TITLE) values ('J2','차장');
Insert into COWORKS.JOB (JOB_CODE,JOB_TITLE) values ('J3','과장');
Insert into COWORKS.JOB (JOB_CODE,JOB_TITLE) values ('J4','주임');
Insert into COWORKS.JOB (JOB_CODE,JOB_TITLE) values ('J5','대리');
Insert into COWORKS.JOB (JOB_CODE,JOB_TITLE) values ('J6','사원');


Insert into COWORKS.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_MGRNO) values ('D01','관리',0);
Insert into COWORKS.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_MGRNO) values ('D02','경영',0);
Insert into COWORKS.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_MGRNO) values ('D03','마케팅',0);
Insert into COWORKS.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_MGRNO) values ('D04','인사',0);
Insert into COWORKS.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_MGRNO) values ('D05','전산',0);
Insert into COWORKS.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_MGRNO) values ('D06','총무',0);
Insert into COWORKS.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_MGRNO) values ('D07','회계',0);


Insert into COWORKS.EMPLOYEE (EMP_NO,EMP_NAME,EMP_PASSWORD,JOB_CODE,DEPT_CODE,EMP_PHONE,EMP_EMAIL,EMP_EMAILPASSWORD,EMP_BIRTH,EMP_GENDER,EMP_HIREDATE,EMP_RESIGNDATE,EMP_ISWORK,EMP_SIGNATURE,EMP_AUTHORITY) values (12345678,'김길동','1234','J1','D01',null,null,null,null,null,null,null,null,null,null);

--------------------------------------------------------
--  DDL for View EMPVIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COWORKS"."EMPVIEW" ("EMP_NO", "EMP_NAME", "EMP_PASSWORD", "JOB_CODE", "DEPT_CODE", "EMP_PHONE", "EMP_EMAIL", "EMP_EMAILPASSWORD", "EMP_BIRTH", "EMP_GENDER", "EMP_HIREDATE", "EMP_RESIGNDATE", "EMP_ISWORK", "EMP_SIGNATURE", "EMP_AUTHORITY", "DEPT_NAME", "JOB_TITLE") AS 
  SELECT 
    employee."EMP_NO",employee."EMP_NAME",employee."EMP_PASSWORD",employee."JOB_CODE",employee."DEPT_CODE",employee."EMP_PHONE",employee."EMP_EMAIL",employee."EMP_EMAILPASSWORD",employee."EMP_BIRTH",employee."EMP_GENDER",employee."EMP_HIREDATE",employee."EMP_RESIGNDATE",employee."EMP_ISWORK",employee."EMP_SIGNATURE",employee."EMP_AUTHORITY",department.dept_name, job_title
FROM 
    employee, department, job
where employee.dept_code=department.dept_code and employee.job_code=job.job_code
;
 CREATE SEQUENCE  "COWORKS"."SEQ_ATTEN_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 48 NOCACHE  NOORDER  NOCYCLE ;


   
   COMMIT;